 
- id: 'terraform-apply'
-  waitFor:
- 'terraform-init-plan'
  name: 'alpine:3.13.3'
  volumes:
- name: 'workout'
  path: '/home/khushalpar/workout'
  dir: '/home/khushalpar/workout'
  entrypoint: 'sh'
  args:
- '-c'
- |
set -eo pipefail
 
 
 
 
 tfenv install
  terraform init
  terraform apply \
-auto-approve \

done
