steps:
- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
   
        terraform init -reconfigure
       
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init -reconfigure || exit 1
          cd ../../
        done
       
